# so we are going to learn about the basic structures.

openapi: 3.0.0
info:
  title: Basic Practice
  description: so this is a basic practice module.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
    
paths:
  /users:
    get:
      summary: it gets the no. of users currently signed up.
      responses:
        '200': # status code
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  type: string
