-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 10:06:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `Email` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingBasket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingBasket` (
  `ID` INT(10) NOT NULL,
  `customerEmail` VARCHAR(255) NOT NULL,
  `customer_Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ShoppingBasket_customer_idx` (`customer_Email` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingBasket_customer`
    FOREIGN KEY (`customer_Email`)
    REFERENCES `mydb`.`customer` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publisher` (
  `Name` VARCHAR(255) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `Phone` VARCHAR(255) NOT NULL,
  `URL` INT(10) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `Name` VARCHAR(255) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Name`, `Address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` VARCHAR(255) NOT NULL,
  `PublisherName` VARCHAR(255) NULL,
  `AuthorName` VARCHAR(255) NULL,
  `AuthorAddress` VARCHAR(255) NULL,
  `Year` INT(10) NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(19,0) NOT NULL,
  `Publisher_Name` VARCHAR(255) NOT NULL,
  `Author_Name` VARCHAR(255) NOT NULL,
  `Author_Address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Book_Publisher1_idx` (`Publisher_Name` ASC) VISIBLE,
  INDEX `fk_Book_Author1_idx` (`Author_Name` ASC, `Author_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Publisher1`
    FOREIGN KEY (`Publisher_Name`)
    REFERENCES `mydb`.`Publisher` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Author1`
    FOREIGN KEY (`Author_Name` , `Author_Address`)
    REFERENCES `mydb`.`Author` (`Name` , `Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingBasket_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingBasket_Book` (
  `ShoppingBasketID` INT(10) NOT NULL,
  `BookISBN` VARCHAR(255) NOT NULL,
  `Count` INT(10) NULL,
  `ShoppingBasket_ID` INT(10) NOT NULL,
  `Book_ISBN` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ShoppingBasketID`, `BookISBN`, `Book_ISBN`),
  INDEX `fk_ShoppingBasket_Book_ShoppingBasket1_idx` (`ShoppingBasket_ID` ASC) VISIBLE,
  INDEX `fk_ShoppingBasket_Book_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingBasket_Book_ShoppingBasket1`
    FOREIGN KEY (`ShoppingBasket_ID`)
    REFERENCES `mydb`.`ShoppingBasket` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingBasket_Book_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `Code` INT(10) NOT NULL,
  `Phone` VARCHAR(255) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WareHouse_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WareHouse_Book` (
  `WareHouseCode` INT(10) NOT NULL,
  `BookISBN` VARCHAR(255) NOT NULL,
  `Count` INT(10) NOT NULL,
  `Warehouse_Code` INT(10) NOT NULL,
  `Book_ISBN` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`WareHouseCode`, `BookISBN`),
  INDEX `fk_WareHouse_Book_Warehouse1_idx` (`Warehouse_Code` ASC) VISIBLE,
  INDEX `fk_WareHouse_Book_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_WareHouse_Book_Warehouse1`
    FOREIGN KEY (`Warehouse_Code`)
    REFERENCES `mydb`.`Warehouse` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WareHouse_Book_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
